// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: Common.proto

package examshare

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ErrCode int32

const (
	ErrCode_ResultSuccess          ErrCode = 0
	ErrCode_ResultFail             ErrCode = 100
	ErrCode_ResultExistUserID      ErrCode = 101
	ErrCode_ResultUserStateErr     ErrCode = 102
	ErrCode_ResultRoomCreateFail   ErrCode = 103
	ErrCode_ResultRoomAlreadyExist ErrCode = 104
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:   "ResultSuccess",
		100: "ResultFail",
		101: "ResultExistUserID",
		102: "ResultUserStateErr",
		103: "ResultRoomCreateFail",
		104: "ResultRoomAlreadyExist",
	}
	ErrCode_value = map[string]int32{
		"ResultSuccess":          0,
		"ResultFail":             100,
		"ResultExistUserID":      101,
		"ResultUserStateErr":     102,
		"ResultRoomCreateFail":   103,
		"ResultRoomAlreadyExist": 104,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_Common_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_Common_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_Common_proto_rawDescGZIP(), []int{0}
}

type SrvType int32

const (
	SrvType_SrvModeZero  SrvType = 0
	SrvType_FrontSrvMode SrvType = 1
	SrvType_ChatSrcMode  SrvType = 2
)

// Enum value maps for SrvType.
var (
	SrvType_name = map[int32]string{
		0: "SrvModeZero",
		1: "FrontSrvMode",
		2: "ChatSrcMode",
	}
	SrvType_value = map[string]int32{
		"SrvModeZero":  0,
		"FrontSrvMode": 1,
		"ChatSrcMode":  2,
	}
)

func (x SrvType) Enum() *SrvType {
	p := new(SrvType)
	*p = x
	return p
}

func (x SrvType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SrvType) Descriptor() protoreflect.EnumDescriptor {
	return file_Common_proto_enumTypes[1].Descriptor()
}

func (SrvType) Type() protoreflect.EnumType {
	return &file_Common_proto_enumTypes[1]
}

func (x SrvType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SrvType.Descriptor instead.
func (SrvType) EnumDescriptor() ([]byte, []int) {
	return file_Common_proto_rawDescGZIP(), []int{1}
}

type SrvModeByIndex int32

const (
	SrvModeByIndex_SrvModeByIndexZero  SrvModeByIndex = 0
	SrvModeByIndex_FrontServerStartIdx SrvModeByIndex = 1
	SrvModeByIndex_ChatServerStartIdx  SrvModeByIndex = 1000
)

// Enum value maps for SrvModeByIndex.
var (
	SrvModeByIndex_name = map[int32]string{
		0:    "SrvModeByIndexZero",
		1:    "FrontServerStartIdx",
		1000: "ChatServerStartIdx",
	}
	SrvModeByIndex_value = map[string]int32{
		"SrvModeByIndexZero":  0,
		"FrontServerStartIdx": 1,
		"ChatServerStartIdx":  1000,
	}
)

func (x SrvModeByIndex) Enum() *SrvModeByIndex {
	p := new(SrvModeByIndex)
	*p = x
	return p
}

func (x SrvModeByIndex) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SrvModeByIndex) Descriptor() protoreflect.EnumDescriptor {
	return file_Common_proto_enumTypes[2].Descriptor()
}

func (SrvModeByIndex) Type() protoreflect.EnumType {
	return &file_Common_proto_enumTypes[2]
}

func (x SrvModeByIndex) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SrvModeByIndex.Descriptor instead.
func (SrvModeByIndex) EnumDescriptor() ([]byte, []int) {
	return file_Common_proto_rawDescGZIP(), []int{2}
}

type Etc int32

const (
	Etc_EtcZero                Etc = 0
	Etc_BuildVer               Etc = 19
	Etc_ExamplePacketSerialkey Etc = 1571406619
)

// Enum value maps for Etc.
var (
	Etc_name = map[int32]string{
		0:          "EtcZero",
		19:         "BuildVer",
		1571406619: "ExamplePacketSerialkey",
	}
	Etc_value = map[string]int32{
		"EtcZero":                0,
		"BuildVer":               19,
		"ExamplePacketSerialkey": 1571406619,
	}
)

func (x Etc) Enum() *Etc {
	p := new(Etc)
	*p = x
	return p
}

func (x Etc) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Etc) Descriptor() protoreflect.EnumDescriptor {
	return file_Common_proto_enumTypes[3].Descriptor()
}

func (Etc) Type() protoreflect.EnumType {
	return &file_Common_proto_enumTypes[3]
}

func (x Etc) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Etc.Descriptor instead.
func (Etc) EnumDescriptor() ([]byte, []int) {
	return file_Common_proto_rawDescGZIP(), []int{3}
}

var File_Common_proto protoreflect.FileDescriptor

var file_Common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x65, 0x78, 0x61, 0x6d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2a, 0x91, 0x01, 0x0a, 0x07, 0x45, 0x72,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x46, 0x61, 0x69, 0x6c, 0x10, 0x64, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x10, 0x65, 0x12,
	0x16, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x45, 0x72, 0x72, 0x10, 0x66, 0x12, 0x18, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x10,
	0x67, 0x12, 0x1a, 0x0a, 0x16, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x41,
	0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10, 0x68, 0x2a, 0x3d, 0x0a,
	0x07, 0x53, 0x72, 0x76, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x72, 0x76, 0x4d,
	0x6f, 0x64, 0x65, 0x5a, 0x65, 0x72, 0x6f, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x46, 0x72, 0x6f,
	0x6e, 0x74, 0x53, 0x72, 0x76, 0x4d, 0x6f, 0x64, 0x65, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x43,
	0x68, 0x61, 0x74, 0x53, 0x72, 0x63, 0x4d, 0x6f, 0x64, 0x65, 0x10, 0x02, 0x2a, 0x5a, 0x0a, 0x0e,
	0x53, 0x72, 0x76, 0x4d, 0x6f, 0x64, 0x65, 0x42, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16,
	0x0a, 0x12, 0x53, 0x72, 0x76, 0x4d, 0x6f, 0x64, 0x65, 0x42, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x5a, 0x65, 0x72, 0x6f, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x49, 0x64, 0x78, 0x10, 0x01, 0x12,
	0x17, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x49, 0x64, 0x78, 0x10, 0xe8, 0x07, 0x2a, 0x40, 0x0a, 0x03, 0x45, 0x74, 0x63, 0x12,
	0x0b, 0x0a, 0x07, 0x45, 0x74, 0x63, 0x5a, 0x65, 0x72, 0x6f, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x56, 0x65, 0x72, 0x10, 0x13, 0x12, 0x1e, 0x0a, 0x16, 0x45, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x6b, 0x65, 0x79, 0x10, 0x9b, 0x86, 0xa7, 0xed, 0x05, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x3b,
	0x65, 0x78, 0x61, 0x6d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_Common_proto_rawDescOnce sync.Once
	file_Common_proto_rawDescData = file_Common_proto_rawDesc
)

func file_Common_proto_rawDescGZIP() []byte {
	file_Common_proto_rawDescOnce.Do(func() {
		file_Common_proto_rawDescData = protoimpl.X.CompressGZIP(file_Common_proto_rawDescData)
	})
	return file_Common_proto_rawDescData
}

var file_Common_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_Common_proto_goTypes = []interface{}{
	(ErrCode)(0),        // 0: examshare.ErrCode
	(SrvType)(0),        // 1: examshare.SrvType
	(SrvModeByIndex)(0), // 2: examshare.SrvModeByIndex
	(Etc)(0),            // 3: examshare.Etc
}
var file_Common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Common_proto_init() }
func file_Common_proto_init() {
	if File_Common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Common_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Common_proto_goTypes,
		DependencyIndexes: file_Common_proto_depIdxs,
		EnumInfos:         file_Common_proto_enumTypes,
	}.Build()
	File_Common_proto = out.File
	file_Common_proto_rawDesc = nil
	file_Common_proto_goTypes = nil
	file_Common_proto_depIdxs = nil
}
