// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: LogicPacket.proto

package examshare

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type F2CS_ServerRegistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Servertype SrvType `protobuf:"varint,1,opt,name=servertype,proto3,enum=examshare.SrvType" json:"servertype,omitempty"`
	Ip         string  `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port       int32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *F2CS_ServerRegistReq) Reset() {
	*x = F2CS_ServerRegistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LogicPacket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *F2CS_ServerRegistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*F2CS_ServerRegistReq) ProtoMessage() {}

func (x *F2CS_ServerRegistReq) ProtoReflect() protoreflect.Message {
	mi := &file_LogicPacket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use F2CS_ServerRegistReq.ProtoReflect.Descriptor instead.
func (*F2CS_ServerRegistReq) Descriptor() ([]byte, []int) {
	return file_LogicPacket_proto_rawDescGZIP(), []int{0}
}

func (x *F2CS_ServerRegistReq) GetServertype() SrvType {
	if x != nil {
		return x.Servertype
	}
	return SrvType_SrvModeZero
}

func (x *F2CS_ServerRegistReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *F2CS_ServerRegistReq) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type CS2F_ServerRegistRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result           ErrCode `protobuf:"varint,1,opt,name=Result,proto3,enum=examshare.ErrCode" json:"Result,omitempty"`
	IssueServerIndex uint32  `protobuf:"varint,2,opt,name=IssueServerIndex,proto3" json:"IssueServerIndex,omitempty"`
}

func (x *CS2F_ServerRegistRes) Reset() {
	*x = CS2F_ServerRegistRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LogicPacket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2F_ServerRegistRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2F_ServerRegistRes) ProtoMessage() {}

func (x *CS2F_ServerRegistRes) ProtoReflect() protoreflect.Message {
	mi := &file_LogicPacket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2F_ServerRegistRes.ProtoReflect.Descriptor instead.
func (*CS2F_ServerRegistRes) Descriptor() ([]byte, []int) {
	return file_LogicPacket_proto_rawDescGZIP(), []int{1}
}

func (x *CS2F_ServerRegistRes) GetResult() ErrCode {
	if x != nil {
		return x.Result
	}
	return ErrCode_ResultSuccess
}

func (x *CS2F_ServerRegistRes) GetIssueServerIndex() uint32 {
	if x != nil {
		return x.IssueServerIndex
	}
	return 0
}

type CS2C_SystemMsgSend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *CS2C_SystemMsgSend) Reset() {
	*x = CS2C_SystemMsgSend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LogicPacket_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2C_SystemMsgSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2C_SystemMsgSend) ProtoMessage() {}

func (x *CS2C_SystemMsgSend) ProtoReflect() protoreflect.Message {
	mi := &file_LogicPacket_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2C_SystemMsgSend.ProtoReflect.Descriptor instead.
func (*CS2C_SystemMsgSend) Descriptor() ([]byte, []int) {
	return file_LogicPacket_proto_rawDescGZIP(), []int{2}
}

func (x *CS2C_SystemMsgSend) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ChatIssueIdx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IssueServerIndex uint32 `protobuf:"varint,1,opt,name=IssueServerIndex,proto3" json:"IssueServerIndex,omitempty"`
}

func (x *ChatIssueIdx) Reset() {
	*x = ChatIssueIdx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LogicPacket_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatIssueIdx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatIssueIdx) ProtoMessage() {}

func (x *ChatIssueIdx) ProtoReflect() protoreflect.Message {
	mi := &file_LogicPacket_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatIssueIdx.ProtoReflect.Descriptor instead.
func (*ChatIssueIdx) Descriptor() ([]byte, []int) {
	return file_LogicPacket_proto_rawDescGZIP(), []int{3}
}

func (x *ChatIssueIdx) GetIssueServerIndex() uint32 {
	if x != nil {
		return x.IssueServerIndex
	}
	return 0
}

type C2CS_LoginUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cidx   *ChatIssueIdx `protobuf:"bytes,1,opt,name=cidx,proto3" json:"cidx,omitempty"`
	UserID string        `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *C2CS_LoginUserReq) Reset() {
	*x = C2CS_LoginUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LogicPacket_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2CS_LoginUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CS_LoginUserReq) ProtoMessage() {}

func (x *C2CS_LoginUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_LogicPacket_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CS_LoginUserReq.ProtoReflect.Descriptor instead.
func (*C2CS_LoginUserReq) Descriptor() ([]byte, []int) {
	return file_LogicPacket_proto_rawDescGZIP(), []int{4}
}

func (x *C2CS_LoginUserReq) GetCidx() *ChatIssueIdx {
	if x != nil {
		return x.Cidx
	}
	return nil
}

func (x *C2CS_LoginUserReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type CS2C_LoginUserRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result ErrCode `protobuf:"varint,1,opt,name=Result,proto3,enum=examshare.ErrCode" json:"Result,omitempty"`
	UserSn uint32  `protobuf:"varint,2,opt,name=UserSn,proto3" json:"UserSn,omitempty"`
	UserID string  `protobuf:"bytes,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *CS2C_LoginUserRes) Reset() {
	*x = CS2C_LoginUserRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LogicPacket_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2C_LoginUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2C_LoginUserRes) ProtoMessage() {}

func (x *CS2C_LoginUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_LogicPacket_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2C_LoginUserRes.ProtoReflect.Descriptor instead.
func (*CS2C_LoginUserRes) Descriptor() ([]byte, []int) {
	return file_LogicPacket_proto_rawDescGZIP(), []int{5}
}

func (x *CS2C_LoginUserRes) GetResult() ErrCode {
	if x != nil {
		return x.Result
	}
	return ErrCode_ResultSuccess
}

func (x *CS2C_LoginUserRes) GetUserSn() uint32 {
	if x != nil {
		return x.UserSn
	}
	return 0
}

func (x *CS2C_LoginUserRes) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type C2CS_LogOutUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cidx   *ChatIssueIdx `protobuf:"bytes,1,opt,name=cidx,proto3" json:"cidx,omitempty"`
	UserID string        `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	UserSn uint32        `protobuf:"varint,3,opt,name=UserSn,proto3" json:"UserSn,omitempty"`
}

func (x *C2CS_LogOutUserReq) Reset() {
	*x = C2CS_LogOutUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LogicPacket_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2CS_LogOutUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CS_LogOutUserReq) ProtoMessage() {}

func (x *C2CS_LogOutUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_LogicPacket_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CS_LogOutUserReq.ProtoReflect.Descriptor instead.
func (*C2CS_LogOutUserReq) Descriptor() ([]byte, []int) {
	return file_LogicPacket_proto_rawDescGZIP(), []int{6}
}

func (x *C2CS_LogOutUserReq) GetCidx() *ChatIssueIdx {
	if x != nil {
		return x.Cidx
	}
	return nil
}

func (x *C2CS_LogOutUserReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *C2CS_LogOutUserReq) GetUserSn() uint32 {
	if x != nil {
		return x.UserSn
	}
	return 0
}

type CS2C_LogOutUserRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result ErrCode `protobuf:"varint,1,opt,name=Result,proto3,enum=examshare.ErrCode" json:"Result,omitempty"`
}

func (x *CS2C_LogOutUserRes) Reset() {
	*x = CS2C_LogOutUserRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LogicPacket_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2C_LogOutUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2C_LogOutUserRes) ProtoMessage() {}

func (x *CS2C_LogOutUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_LogicPacket_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2C_LogOutUserRes.ProtoReflect.Descriptor instead.
func (*CS2C_LogOutUserRes) Descriptor() ([]byte, []int) {
	return file_LogicPacket_proto_rawDescGZIP(), []int{7}
}

func (x *CS2C_LogOutUserRes) GetResult() ErrCode {
	if x != nil {
		return x.Result
	}
	return ErrCode_ResultSuccess
}

type C2CS_LobbySendMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg    string `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	UserSn uint32 `protobuf:"varint,2,opt,name=UserSn,proto3" json:"UserSn,omitempty"`
}

func (x *C2CS_LobbySendMsgReq) Reset() {
	*x = C2CS_LobbySendMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LogicPacket_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2CS_LobbySendMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CS_LobbySendMsgReq) ProtoMessage() {}

func (x *C2CS_LobbySendMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_LogicPacket_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CS_LobbySendMsgReq.ProtoReflect.Descriptor instead.
func (*C2CS_LobbySendMsgReq) Descriptor() ([]byte, []int) {
	return file_LogicPacket_proto_rawDescGZIP(), []int{8}
}

func (x *C2CS_LobbySendMsgReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *C2CS_LobbySendMsgReq) GetUserSn() uint32 {
	if x != nil {
		return x.UserSn
	}
	return 0
}

type CS2C_LobbySendMsgRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result ErrCode `protobuf:"varint,1,opt,name=Result,proto3,enum=examshare.ErrCode" json:"Result,omitempty"`
	UserID string  `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Msg    string  `protobuf:"bytes,3,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *CS2C_LobbySendMsgRes) Reset() {
	*x = CS2C_LobbySendMsgRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LogicPacket_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2C_LobbySendMsgRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2C_LobbySendMsgRes) ProtoMessage() {}

func (x *CS2C_LobbySendMsgRes) ProtoReflect() protoreflect.Message {
	mi := &file_LogicPacket_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2C_LobbySendMsgRes.ProtoReflect.Descriptor instead.
func (*CS2C_LobbySendMsgRes) Descriptor() ([]byte, []int) {
	return file_LogicPacket_proto_rawDescGZIP(), []int{9}
}

func (x *CS2C_LobbySendMsgRes) GetResult() ErrCode {
	if x != nil {
		return x.Result
	}
	return ErrCode_ResultSuccess
}

func (x *CS2C_LobbySendMsgRes) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *CS2C_LobbySendMsgRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type C2CS_RoomCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomName string `protobuf:"bytes,1,opt,name=RoomName,proto3" json:"RoomName,omitempty"`
	UserSn   uint32 `protobuf:"varint,2,opt,name=UserSn,proto3" json:"UserSn,omitempty"`
}

func (x *C2CS_RoomCreateReq) Reset() {
	*x = C2CS_RoomCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LogicPacket_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2CS_RoomCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CS_RoomCreateReq) ProtoMessage() {}

func (x *C2CS_RoomCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_LogicPacket_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CS_RoomCreateReq.ProtoReflect.Descriptor instead.
func (*C2CS_RoomCreateReq) Descriptor() ([]byte, []int) {
	return file_LogicPacket_proto_rawDescGZIP(), []int{10}
}

func (x *C2CS_RoomCreateReq) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *C2CS_RoomCreateReq) GetUserSn() uint32 {
	if x != nil {
		return x.UserSn
	}
	return 0
}

type CS2C_RoomCreateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result      ErrCode `protobuf:"varint,1,opt,name=Result,proto3,enum=examshare.ErrCode" json:"Result,omitempty"`
	RoomIdx     uint32  `protobuf:"varint,2,opt,name=RoomIdx,proto3" json:"RoomIdx,omitempty"`
	RoomName    string  `protobuf:"bytes,3,opt,name=RoomName,proto3" json:"RoomName,omitempty"`
	EnterUserSn uint32  `protobuf:"varint,4,opt,name=EnterUserSn,proto3" json:"EnterUserSn,omitempty"`
	EnterUserID string  `protobuf:"bytes,5,opt,name=EnterUserID,proto3" json:"EnterUserID,omitempty"`
}

func (x *CS2C_RoomCreateRes) Reset() {
	*x = CS2C_RoomCreateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LogicPacket_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2C_RoomCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2C_RoomCreateRes) ProtoMessage() {}

func (x *CS2C_RoomCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_LogicPacket_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2C_RoomCreateRes.ProtoReflect.Descriptor instead.
func (*CS2C_RoomCreateRes) Descriptor() ([]byte, []int) {
	return file_LogicPacket_proto_rawDescGZIP(), []int{11}
}

func (x *CS2C_RoomCreateRes) GetResult() ErrCode {
	if x != nil {
		return x.Result
	}
	return ErrCode_ResultSuccess
}

func (x *CS2C_RoomCreateRes) GetRoomIdx() uint32 {
	if x != nil {
		return x.RoomIdx
	}
	return 0
}

func (x *CS2C_RoomCreateRes) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *CS2C_RoomCreateRes) GetEnterUserSn() uint32 {
	if x != nil {
		return x.EnterUserSn
	}
	return 0
}

func (x *CS2C_RoomCreateRes) GetEnterUserID() string {
	if x != nil {
		return x.EnterUserID
	}
	return ""
}

type C2CS_RoomEnterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomName string `protobuf:"bytes,1,opt,name=RoomName,proto3" json:"RoomName,omitempty"`
	UserSn   uint32 `protobuf:"varint,2,opt,name=UserSn,proto3" json:"UserSn,omitempty"`
}

func (x *C2CS_RoomEnterReq) Reset() {
	*x = C2CS_RoomEnterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LogicPacket_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2CS_RoomEnterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CS_RoomEnterReq) ProtoMessage() {}

func (x *C2CS_RoomEnterReq) ProtoReflect() protoreflect.Message {
	mi := &file_LogicPacket_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CS_RoomEnterReq.ProtoReflect.Descriptor instead.
func (*C2CS_RoomEnterReq) Descriptor() ([]byte, []int) {
	return file_LogicPacket_proto_rawDescGZIP(), []int{12}
}

func (x *C2CS_RoomEnterReq) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *C2CS_RoomEnterReq) GetUserSn() uint32 {
	if x != nil {
		return x.UserSn
	}
	return 0
}

type CS2C_RoomEnterRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result      ErrCode `protobuf:"varint,1,opt,name=Result,proto3,enum=examshare.ErrCode" json:"Result,omitempty"`
	RoomIdx     uint32  `protobuf:"varint,2,opt,name=RoomIdx,proto3" json:"RoomIdx,omitempty"`
	RoomName    string  `protobuf:"bytes,3,opt,name=RoomName,proto3" json:"RoomName,omitempty"`
	EnterUserSn uint32  `protobuf:"varint,4,opt,name=EnterUserSn,proto3" json:"EnterUserSn,omitempty"`
	EnterUserID string  `protobuf:"bytes,5,opt,name=EnterUserID,proto3" json:"EnterUserID,omitempty"`
}

func (x *CS2C_RoomEnterRes) Reset() {
	*x = CS2C_RoomEnterRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LogicPacket_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2C_RoomEnterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2C_RoomEnterRes) ProtoMessage() {}

func (x *CS2C_RoomEnterRes) ProtoReflect() protoreflect.Message {
	mi := &file_LogicPacket_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2C_RoomEnterRes.ProtoReflect.Descriptor instead.
func (*CS2C_RoomEnterRes) Descriptor() ([]byte, []int) {
	return file_LogicPacket_proto_rawDescGZIP(), []int{13}
}

func (x *CS2C_RoomEnterRes) GetResult() ErrCode {
	if x != nil {
		return x.Result
	}
	return ErrCode_ResultSuccess
}

func (x *CS2C_RoomEnterRes) GetRoomIdx() uint32 {
	if x != nil {
		return x.RoomIdx
	}
	return 0
}

func (x *CS2C_RoomEnterRes) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *CS2C_RoomEnterRes) GetEnterUserSn() uint32 {
	if x != nil {
		return x.EnterUserSn
	}
	return 0
}

func (x *CS2C_RoomEnterRes) GetEnterUserID() string {
	if x != nil {
		return x.EnterUserID
	}
	return ""
}

type C2CS_RoomLeaveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSn uint32 `protobuf:"varint,1,opt,name=UserSn,proto3" json:"UserSn,omitempty"`
}

func (x *C2CS_RoomLeaveReq) Reset() {
	*x = C2CS_RoomLeaveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LogicPacket_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2CS_RoomLeaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CS_RoomLeaveReq) ProtoMessage() {}

func (x *C2CS_RoomLeaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_LogicPacket_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CS_RoomLeaveReq.ProtoReflect.Descriptor instead.
func (*C2CS_RoomLeaveReq) Descriptor() ([]byte, []int) {
	return file_LogicPacket_proto_rawDescGZIP(), []int{14}
}

func (x *C2CS_RoomLeaveReq) GetUserSn() uint32 {
	if x != nil {
		return x.UserSn
	}
	return 0
}

type CS2C_RoomLeaveRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result      ErrCode `protobuf:"varint,1,opt,name=Result,proto3,enum=examshare.ErrCode" json:"Result,omitempty"`
	LeaveUserSn uint32  `protobuf:"varint,2,opt,name=LeaveUserSn,proto3" json:"LeaveUserSn,omitempty"`
	LeaveUserID string  `protobuf:"bytes,3,opt,name=LeaveUserID,proto3" json:"LeaveUserID,omitempty"`
}

func (x *CS2C_RoomLeaveRes) Reset() {
	*x = CS2C_RoomLeaveRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LogicPacket_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2C_RoomLeaveRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2C_RoomLeaveRes) ProtoMessage() {}

func (x *CS2C_RoomLeaveRes) ProtoReflect() protoreflect.Message {
	mi := &file_LogicPacket_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2C_RoomLeaveRes.ProtoReflect.Descriptor instead.
func (*CS2C_RoomLeaveRes) Descriptor() ([]byte, []int) {
	return file_LogicPacket_proto_rawDescGZIP(), []int{15}
}

func (x *CS2C_RoomLeaveRes) GetResult() ErrCode {
	if x != nil {
		return x.Result
	}
	return ErrCode_ResultSuccess
}

func (x *CS2C_RoomLeaveRes) GetLeaveUserSn() uint32 {
	if x != nil {
		return x.LeaveUserSn
	}
	return 0
}

func (x *CS2C_RoomLeaveRes) GetLeaveUserID() string {
	if x != nil {
		return x.LeaveUserID
	}
	return ""
}

type C2CS_RoomSendMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomIdx uint32 `protobuf:"varint,1,opt,name=RoomIdx,proto3" json:"RoomIdx,omitempty"`
	Msg     string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	UserSn  uint32 `protobuf:"varint,3,opt,name=UserSn,proto3" json:"UserSn,omitempty"`
}

func (x *C2CS_RoomSendMsgReq) Reset() {
	*x = C2CS_RoomSendMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LogicPacket_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2CS_RoomSendMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CS_RoomSendMsgReq) ProtoMessage() {}

func (x *C2CS_RoomSendMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_LogicPacket_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CS_RoomSendMsgReq.ProtoReflect.Descriptor instead.
func (*C2CS_RoomSendMsgReq) Descriptor() ([]byte, []int) {
	return file_LogicPacket_proto_rawDescGZIP(), []int{16}
}

func (x *C2CS_RoomSendMsgReq) GetRoomIdx() uint32 {
	if x != nil {
		return x.RoomIdx
	}
	return 0
}

func (x *C2CS_RoomSendMsgReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *C2CS_RoomSendMsgReq) GetUserSn() uint32 {
	if x != nil {
		return x.UserSn
	}
	return 0
}

type CS2C_RoomSendMsgRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result ErrCode `protobuf:"varint,1,opt,name=Result,proto3,enum=examshare.ErrCode" json:"Result,omitempty"`
	Userid string  `protobuf:"bytes,2,opt,name=Userid,proto3" json:"Userid,omitempty"`
	Msg    string  `protobuf:"bytes,3,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *CS2C_RoomSendMsgRes) Reset() {
	*x = CS2C_RoomSendMsgRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LogicPacket_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2C_RoomSendMsgRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2C_RoomSendMsgRes) ProtoMessage() {}

func (x *CS2C_RoomSendMsgRes) ProtoReflect() protoreflect.Message {
	mi := &file_LogicPacket_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2C_RoomSendMsgRes.ProtoReflect.Descriptor instead.
func (*CS2C_RoomSendMsgRes) Descriptor() ([]byte, []int) {
	return file_LogicPacket_proto_rawDescGZIP(), []int{17}
}

func (x *CS2C_RoomSendMsgRes) GetResult() ErrCode {
	if x != nil {
		return x.Result
	}
	return ErrCode_ResultSuccess
}

func (x *CS2C_RoomSendMsgRes) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *CS2C_RoomSendMsgRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_LogicPacket_proto protoreflect.FileDescriptor

var file_LogicPacket_proto_rawDesc = []byte{
	0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x65, 0x78, 0x61, 0x6d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x1a, 0x0c,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x14,
	0x46, 0x32, 0x43, 0x53, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x32, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x2e, 0x53, 0x72, 0x76, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x6e, 0x0a, 0x14,
	0x43, 0x53, 0x32, 0x46, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x2a, 0x0a, 0x10, 0x49, 0x73, 0x73, 0x75, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x49, 0x73, 0x73, 0x75,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x26, 0x0a, 0x12,
	0x43, 0x53, 0x32, 0x43, 0x5f, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x73, 0x67, 0x53, 0x65,
	0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x4d, 0x73, 0x67, 0x22, 0x3a, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x74, 0x49, 0x73, 0x73, 0x75,
	0x65, 0x49, 0x64, 0x78, 0x12, 0x2a, 0x0a, 0x10, 0x49, 0x73, 0x73, 0x75, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10,
	0x49, 0x73, 0x73, 0x75, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x22, 0x58, 0x0a, 0x11, 0x43, 0x32, 0x43, 0x53, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x04, 0x63, 0x69, 0x64, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e,
	0x63, 0x68, 0x61, 0x74, 0x49, 0x73, 0x73, 0x75, 0x65, 0x49, 0x64, 0x78, 0x52, 0x04, 0x63, 0x69,
	0x64, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x6f, 0x0a, 0x11, 0x43, 0x53,
	0x32, 0x43, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12,
	0x2a, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x71, 0x0a, 0x12, 0x43,
	0x32, 0x43, 0x53, 0x5f, 0x4c, 0x6f, 0x67, 0x4f, 0x75, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x12, 0x2b, 0x0a, 0x04, 0x63, 0x69, 0x64, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x49, 0x73, 0x73, 0x75, 0x65, 0x49, 0x64, 0x78, 0x52, 0x04, 0x63, 0x69, 0x64, 0x78, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x53, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x53, 0x6e, 0x22, 0x40,
	0x0a, 0x12, 0x43, 0x53, 0x32, 0x43, 0x5f, 0x4c, 0x6f, 0x67, 0x4f, 0x75, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x40, 0x0a, 0x14, 0x43, 0x32, 0x43, 0x53, 0x5f, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x6e, 0x22, 0x6c, 0x0a, 0x14, 0x43, 0x53, 0x32, 0x43, 0x5f, 0x4c, 0x6f, 0x62, 0x62, 0x79,
	0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x65, 0x78, 0x61,
	0x6d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x10,
	0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67,
	0x22, 0x48, 0x0a, 0x12, 0x43, 0x32, 0x43, 0x53, 0x5f, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x53, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x53, 0x6e, 0x22, 0xba, 0x01, 0x0a, 0x12, 0x43,
	0x53, 0x32, 0x43, 0x5f, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x12, 0x2a, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x12, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x45, 0x72,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x45, 0x6e, 0x74, 0x65,
	0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x47, 0x0a, 0x11, 0x43, 0x32, 0x43, 0x53, 0x5f,
	0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08,
	0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x53, 0x6e,
	0x22, 0xb9, 0x01, 0x0a, 0x11, 0x43, 0x53, 0x32, 0x43, 0x5f, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x6e,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x78, 0x12, 0x1a, 0x0a, 0x08,
	0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x45, 0x6e, 0x74, 0x65,
	0x72, 0x55, 0x73, 0x65, 0x72, 0x53, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x45,
	0x6e, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x53, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x45, 0x6e,
	0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x2b, 0x0a, 0x11,
	0x43, 0x32, 0x43, 0x53, 0x5f, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x53, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x53, 0x6e, 0x22, 0x83, 0x01, 0x0a, 0x11, 0x43, 0x53,
	0x32, 0x43, 0x5f, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x12,
	0x2a, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x4c,
	0x65, 0x61, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x6e, 0x12, 0x20, 0x0a,
	0x0b, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22,
	0x59, 0x0a, 0x13, 0x43, 0x32, 0x43, 0x53, 0x5f, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x6e, 0x64,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x78,
	0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d,
	0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x53, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x53, 0x6e, 0x22, 0x6b, 0x0a, 0x13, 0x43, 0x53,
	0x32, 0x43, 0x5f, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65,
	0x73, 0x12, 0x2a, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x12, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x45, 0x72,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x3b, 0x65, 0x78, 0x61,
	0x6d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_LogicPacket_proto_rawDescOnce sync.Once
	file_LogicPacket_proto_rawDescData = file_LogicPacket_proto_rawDesc
)

func file_LogicPacket_proto_rawDescGZIP() []byte {
	file_LogicPacket_proto_rawDescOnce.Do(func() {
		file_LogicPacket_proto_rawDescData = protoimpl.X.CompressGZIP(file_LogicPacket_proto_rawDescData)
	})
	return file_LogicPacket_proto_rawDescData
}

var file_LogicPacket_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_LogicPacket_proto_goTypes = []interface{}{
	(*F2CS_ServerRegistReq)(nil), // 0: examshare.F2CS_ServerRegistReq
	(*CS2F_ServerRegistRes)(nil), // 1: examshare.CS2F_ServerRegistRes
	(*CS2C_SystemMsgSend)(nil),   // 2: examshare.CS2C_SystemMsgSend
	(*ChatIssueIdx)(nil),         // 3: examshare.chatIssueIdx
	(*C2CS_LoginUserReq)(nil),    // 4: examshare.C2CS_LoginUserReq
	(*CS2C_LoginUserRes)(nil),    // 5: examshare.CS2C_LoginUserRes
	(*C2CS_LogOutUserReq)(nil),   // 6: examshare.C2CS_LogOutUserReq
	(*CS2C_LogOutUserRes)(nil),   // 7: examshare.CS2C_LogOutUserRes
	(*C2CS_LobbySendMsgReq)(nil), // 8: examshare.C2CS_LobbySendMsgReq
	(*CS2C_LobbySendMsgRes)(nil), // 9: examshare.CS2C_LobbySendMsgRes
	(*C2CS_RoomCreateReq)(nil),   // 10: examshare.C2CS_RoomCreateReq
	(*CS2C_RoomCreateRes)(nil),   // 11: examshare.CS2C_RoomCreateRes
	(*C2CS_RoomEnterReq)(nil),    // 12: examshare.C2CS_RoomEnterReq
	(*CS2C_RoomEnterRes)(nil),    // 13: examshare.CS2C_RoomEnterRes
	(*C2CS_RoomLeaveReq)(nil),    // 14: examshare.C2CS_RoomLeaveReq
	(*CS2C_RoomLeaveRes)(nil),    // 15: examshare.CS2C_RoomLeaveRes
	(*C2CS_RoomSendMsgReq)(nil),  // 16: examshare.C2CS_RoomSendMsgReq
	(*CS2C_RoomSendMsgRes)(nil),  // 17: examshare.CS2C_RoomSendMsgRes
	(SrvType)(0),                 // 18: examshare.SrvType
	(ErrCode)(0),                 // 19: examshare.ErrCode
}
var file_LogicPacket_proto_depIdxs = []int32{
	18, // 0: examshare.F2CS_ServerRegistReq.servertype:type_name -> examshare.SrvType
	19, // 1: examshare.CS2F_ServerRegistRes.Result:type_name -> examshare.ErrCode
	3,  // 2: examshare.C2CS_LoginUserReq.cidx:type_name -> examshare.chatIssueIdx
	19, // 3: examshare.CS2C_LoginUserRes.Result:type_name -> examshare.ErrCode
	3,  // 4: examshare.C2CS_LogOutUserReq.cidx:type_name -> examshare.chatIssueIdx
	19, // 5: examshare.CS2C_LogOutUserRes.Result:type_name -> examshare.ErrCode
	19, // 6: examshare.CS2C_LobbySendMsgRes.Result:type_name -> examshare.ErrCode
	19, // 7: examshare.CS2C_RoomCreateRes.Result:type_name -> examshare.ErrCode
	19, // 8: examshare.CS2C_RoomEnterRes.Result:type_name -> examshare.ErrCode
	19, // 9: examshare.CS2C_RoomLeaveRes.Result:type_name -> examshare.ErrCode
	19, // 10: examshare.CS2C_RoomSendMsgRes.Result:type_name -> examshare.ErrCode
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_LogicPacket_proto_init() }
func file_LogicPacket_proto_init() {
	if File_LogicPacket_proto != nil {
		return
	}
	file_Common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_LogicPacket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*F2CS_ServerRegistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LogicPacket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2F_ServerRegistRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LogicPacket_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2C_SystemMsgSend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LogicPacket_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatIssueIdx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LogicPacket_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2CS_LoginUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LogicPacket_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2C_LoginUserRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LogicPacket_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2CS_LogOutUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LogicPacket_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2C_LogOutUserRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LogicPacket_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2CS_LobbySendMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LogicPacket_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2C_LobbySendMsgRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LogicPacket_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2CS_RoomCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LogicPacket_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2C_RoomCreateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LogicPacket_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2CS_RoomEnterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LogicPacket_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2C_RoomEnterRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LogicPacket_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2CS_RoomLeaveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LogicPacket_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2C_RoomLeaveRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LogicPacket_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2CS_RoomSendMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LogicPacket_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2C_RoomSendMsgRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_LogicPacket_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_LogicPacket_proto_goTypes,
		DependencyIndexes: file_LogicPacket_proto_depIdxs,
		MessageInfos:      file_LogicPacket_proto_msgTypes,
	}.Build()
	File_LogicPacket_proto = out.File
	file_LogicPacket_proto_rawDesc = nil
	file_LogicPacket_proto_goTypes = nil
	file_LogicPacket_proto_depIdxs = nil
}
